### ISSUE TITLE
refactor: Controller to use MVC pattern properly

### ISSUE THREAD

**Issue by clstaudt** [tuttle-dev/tuttle#76]

**Comment by clstaudt** [comment]
@vlad-ed-git  I don't think the explanation in the accepted answer is particularly clear. e.g. What is now the relationship between a state machine and MVI?

https://stackoverflow.com/questions/59205614/what-is-the-difference-between-mvi-compared-to-mvc-and-mvvm

Will do some more reading on the topic and we should discuss it based on Tuttle code and your implementation.

**Comment by vlad-ed-git** [comment]
Oh okay, I actually tried to find better articles (that are brief) and
thought this was the clearest.
But of course, it makes more sense when you look at code (and it is much
easier).
I have sent you an email on a discussion meeting.

**Comment by clstaudt** [comment]
@vlad-ed-git  I need to have a closer look at this and implement some functionality using your new architecture, only then can I give an informed opinion.

**Comment by vlad-ed-git** [comment]
Yes. You can basically start with implementing the data sources and working
with the models. (Two files per feature, e.g. user model and it's data
source).

**Comment by clstaudt** [comment]
@vlad-ed-git   A question about your coding style: What is the advantage of centralizing all strings in a module?

On the downside:
- every string needs a name - naming things and remembering names -> overhead
- one more level of indirection -> code complexity
- code harder to search and harder to read

**Comment by clstaudt** [comment]
@vlad-ed-git If translation is the only reason, then I believe there is a more elegant alternative:
https://babel.pocoo.org/en/latest/messages.html

I don't have practical experience with this though - any thoughts?

Regarding code readability I would prefer inlined strings.

**Comment by vlad-ed-git** [comment]
I have no experience with Babel either.
I shall make the strings inline then. Some already are (I have been
refactoring to edit that, but I shall revert them back to inline).

**Comment by vlad-ed-git** [comment]
I will just manually replace them, there aren't that many strings.

**Comment by clstaudt** [comment]
Okay. Topic of internationalization will come up at a later point in the future, not a priority now.

**Comment by clstaudt** [comment]
@vlad-ed-git  I would like to add new screens, selected from the second menu. 

How should I do that?

I don't understand why there are two copies of the code, one for each menu. What if we want a "third menu" - actually only another group of menu items with a different headline?  Implement `on_tertiary_menu_change` etc.?  Can this redundancy be avoided here?

![Image](https://user-images.githubusercontent.com/875194/206478661-3431a6d1-9efe-4b4f-bc43-59e5a95f11aa.png)

**Comment by clstaudt** [comment]
Some simple questions, but I have spent time searching through the code and the solution was not clear to me:

- Q: Where can I decrease the font size for the menu items and decrease the spacing between them as well?

![Image](https://user-images.githubusercontent.com/875194/206502321-a32b0512-e618-47d6-9561-21e2533d1854.png)

- Q: How can I remove the background color of the main container?

![Image](https://user-images.githubusercontent.com/875194/206502850-53579602-6a7f-4f4a-8526-2037fb93aad6.png)

**Comment by clstaudt** [comment]
- Q: If I want to add a new menu item "Dashboard" that comes first, what should I do?


![Image](https://user-images.githubusercontent.com/875194/206511024-1649fec5-66b7-44c5-a285-fc98dc6b37d5.png)

![Image](https://user-images.githubusercontent.com/875194/206512181-b1976017-2269-41ad-af6b-8c2a06f0dae7.png)

I think I should challenge the enum-based implementation of the menu and possibly replace it with something more declarative in style. Would not something like this be possible and more straightforward?

```
menu_items = [
    {
        "label": "Dashboard",
        "icon": icons.SPEED_OUTLINED,
        "icon_selected": icons.SPEED,
        "destination": go_to_dashboard_callback,
    },
    {
        "label": "Projects",
        "icon": icons.FOLDER_OUTLINED,
        "icon_selected": icons.FOLDER,
        "destination": go_to_projects_callback,
    },
]
```

**Comment by vlad-ed-git** [comment]
- Q: How can I remove the background color of the main container?
The main container is a card with a container in it. the current background color is the default one generated based on the theme. To change it, supply the container (_**self.destination_content_container**_) with the color you want by setting the property **bgcolor** to "CUSTOM_HEX_COLOR". *This color should work for the dark or light theme as users can set their theme preference to "system", which could be dark/light.

**Comment by vlad-ed-git** [comment]
-I think I should challenge the enum-based implementation of the menu and possibly replace it with something more declarative in style.-
You can try that approach yes.

**Comment by vlad-ed-git** [comment]
Q: If I want to add a new menu item "Dashboard" that comes first, what should I do?
- The first item is the one indexed as zero. You would add it to enum 1, then specify its corresponding view, icon, selected_icon, label,  and how clicking 'new' is handled when the user is within this menu (**_get_new_main_item_route_or_intent_**) by defining the route (string) to go to (if they should be taken to a new view entirely as in the case for clicking new project) OR an intent (string) to go to if an intent should be passed to the child view instead (which will handle it typically by showing a pop up with a "create new" form). 
*As this is a dashboard, then I am guessing you will want to update the action bar to hide the new button while on this view.

**Comment by vlad-ed-git** [comment]
@clstaudt please check my latest code push, I refactored the code for the side menu, and most of the above comments will be invalid in the new approach.

**Comment by clstaudt** [comment]
Refactoring of the menu: nicely declarative, thanks

**Comment by clstaudt** [comment]
@vlad-ed-git  This may be a matter of taste, but there are already too many .py files for my taste in the project. I think it's not pythonic. And the number will multiply if development continues with this pattern. I am thinking about how to refactor to reduce the number of files.

Consider the clients module:

![Image](https://user-images.githubusercontent.com/875194/206854093-0462c10a-f0c1-46ba-bdba-196d0f117a52.png)

Since the architecture pattern is MVI, why not:

```
client/
    __init__.py
   model.py
   view.py
   intent.py
````

Would that work?

**Comment by clstaudt** [comment]
@vlad-ed-git  Q: What is the benefit of having separate classes for interface and implementation? When does the payoff for using this pattern come? 

In statically typed languages this design pattern is used so that you can substitute implementations of an interface, even at runtime. I wonder whether the pattern is generally unnecessary in Python, because Python uses duck typing anyway.

**Comment by clstaudt** [comment]
@vlad-ed-git  I have to say I'm still confused by the design patterns here.

```python
class ClientsIntentImpl(ClientsIntent):
    def __init__(self, local_storage: ClientStorage):
        super().__init__(
            data_source=ClientDataSourceImpl(), local_storage=local_storage
        )
        self.contacts_data_source = ContactDataSourceImpl()
```

For example, why are there two instantiations of ContactDataSourceImpl ? Why does ClientsIntentImpl need two copies of the same object?

Can we meet some time to get me started with implementing the backend connection?

**Comment by clstaudt** [comment]
@vlad-ed-git  I think it's more than coding style, it's software architecture and we need to have a short debate about it. I'd like you to remove the abstractions if we have a consensus that they are more overhead than benefit.

**Comment by clstaudt** [comment]
@vlad-ed-git 

I made several attempts to integrate the database in the MVI pattern, but I have to put it on hold because after spending hours with your pattern I still don't get it.

For example, I'm confused: What is the role of IntentResult? When should a method return the data and when should it return an IntentResult? Here it seems arbitrarily mixed:



![Image](https://user-images.githubusercontent.com/875194/208298502-dae9ab29-7397-4ea1-9da2-5c50a3d0a2db.png)

**Comment by vlad-ed-git** [comment]
ALL data-source methods MUST return results for all intents as an
IntentResult, it is meant to be a wrapper for the data returned (if any),
and error plus log messages (if any).
If there is a data source method that returns any other type, then it's a
mistake on my part.
The data source will either specify the data or the log message (if the
intent was not successful) which is typically logged into a file or sent
back for analytics if the app uses the internet.

The error message is set by the Intent class and it is the one shown to the
user.

*However, in some instances the Intent class might not want to show any
error message to the user (typically because the UI will intuitively
represent an error state and an alert or snack message would just be
redundant), so the intent class methods can sometimes NOT return an Intent
Result.
*In the case you screenshotted, the user is requesting to view all
contacts. If something goes wrong, no contacts will be returned and the
page will say "You have not set any contacts" and it will be empty. To the
user either
1. Yes they didn't actually add any contacts
OR
2. They have added contacts and something is wrong. - They will go on to
report as -"It fails to retrieve contacts I have created".
This is one of those cases where an extra error message saying "something
went wrong retrieving contacts" seems redundant so the Intent class does
not set any error message.

Let me know which other part is unclear.
But essentially, MVI works simply as this:

   1. the view requests data from the data source by issuing an intent
   request. e.g. get-all-contacts
   2. the intent handles actually calling the data source and mapping the
   data from the data source to a form that is usable for the view (hence the
   intent can return data in multiple ways).
   3. the data source (commonly known as the repository) receives intent
   requests,  decides the source to search data from (internet API or local
   database or local storage, etc), fetches data from that store, and returns
   it to the view via an intent handler.  The data source must specify if
   something went wrong with the request and if any data is returned as part
   of the request-response. *The data source returns responses to the view in
   a uniform manner (in our case we use the IntentResult wrapper).

**Comment by clstaudt** [comment]
@vlad-ed-git  Thanks for the explanation of MVI. It's the clearest one I got so far, and I have been looking. 

Naming is tricky here. An intent is a method while the class named XYZIntent is an intent handler...

I am trying to attach the database to the data sources. Here I think are some fundamental architecture decisions to be made that I would like to run past you when you are available.

For example: Intuitively the database connector (an instance of SQLAlchemy Engine) is a property of TuttleApp. So a DataSource should know its TuttleApp instance to access it, right? If so, how to handle circular dependency issues with the current architecture. TBD.
