### ISSUE TITLE
View: Projects List with status filter

### ISSUE THREAD

**Issue by vlad-ed-git** [tuttle-dev/tuttle#80]

**Comment by clstaudt** [comment]
I like how the projects are displayed as tiles.

Feature request for next phase: I want to change the controls for the filter so that they do not look like just another set of buttons, but it's clear that these are mutually exclusive filter settings. Any ideas?

![Image](https://user-images.githubusercontent.com/875194/204138682-872f6bf6-f566-4831-a93d-951c38683100.png)

**Comment by vlad-ed-git** [comment]
Let me think on this.

**Comment by clstaudt** [comment]
Maybe tabs? https://flet.dev/docs/controls/tabs

**Comment by vlad-ed-git** [comment]
Yes we could use tabs

**Comment by vlad-ed-git** [comment]
closing this, as the requested feature will be part of a future phase.
